name: CosmoCode
on:
  workflow_dispatch:
    inputs:
      testFile:
        description: 'Select test file to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - cosmocode.spec.js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install Dependencies
        run: npm install
      - name: Run Selected Test
        run: |
          npx wdio run ./wdio.conf.js --spec ${{ github.event.inputs.testFile }}
      - name: Install encode-decode-data
        run: npm install -g encode-decode-data
      - name: Display encoded url
        run: |
          url=$(node -e "console.log(require('./test/testData/testData.json').url)")
          encoded_url=$(enc-dec enc "$url" -s hex)
          echo "### Encoded Data Summary" >> $GITHUB_STEP_SUMMARY
          echo "URL: $encoded_url" >> $GITHUB_STEP_SUMMARY
        shell: bash